apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: w1hiewgdl-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: w1hiewgdl-go 
  name: w1hiewgdl-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: w1hiewgdl-go 
